[package]
name = "camera-center"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version="0.4.21", features=["kv"]}
std-logger = "0.5.3"
crossbeam-queue = "0.3.11"
